### ISSUE TITLE
how to solve this?

### ISSUE THREAD

**Issue by liamxg** [esdarling/Misc-R-code#1]
Dear @esdarling,

Could you please tell me how to deal with this:

<img width="1298" alt="image" src="https://github.com/esdarling/Misc-R-code/assets/46078579/bc6e831a-a948-4501-8f52-326ca8b827f3">

Thanks.

**Comment by esdarling** [comment]
Hi Liam, this seems like the code / original libraries may be deprecated. I suggest you look for help online, good luck!

**Comment by liamxg** [comment]
Hi,
Thanks for your reply and suggestions.
